name: Test against MUSE2
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  test_release:
    name: Latest MUSE2 release
    uses: ./.github/workflows/test-with-muse2.yml
    with:
      muse2_source: release
    secrets: inherit

  test_main:
    name: Current MUSE2 main branch
    uses: ./.github/workflows/test-with-muse2.yml
    with:
      muse2_source: main
    secrets: inherit
