name: Test and build
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  test_release:
    name: Test against latest MUSE2 release
    uses: ./.github/workflows/test-with-muse2.yml
    with:
      muse2_source: release
    secrets: inherit

  test_main:
    name: Test against MUSE2 main
    uses: ./.github/workflows/test-with-muse2.yml
    with:
      muse2_source: main
    secrets: inherit
